name: yourwellbeing
description: A health application which provides details about vulnerable diseases with additional features like booking appointment and messaging service with Health Expert.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  provider: ^6.0.0
  sizer: ^2.0.15
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.0.3
  curved_navigation_bar: ^1.0.2
  flutter_local_notifications: ^8.2.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.0.8
  intl:
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.17
  flutter_spinkit: ^5.1.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Slider/

  fonts:
    - family: NutinoSansBold
      fonts:
        - asset: fonts/nutinosans_bold.ttf

    - family: NutinoSansReg
      fonts:
        - asset: fonts/nutinosans_regular.ttf

    - family: NutinoSansSemiBold
      fonts:
        - asset: fonts/nutinosans_semibold.ttf
