///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyRegisterCreated = 'created';
const String _jsonKeyRegisterUser = 'user';
const String _jsonKeyRegisterToken = 'token';
const String _jsonKeyRegisterUserName = 'name';
const String _jsonKeyRegisterUserEmail = 'email';
const String _jsonKeyRegisterUserUpdatedAt = 'updated_at';
const String _jsonKeyRegisterUserCreatedAt = 'created_at';
const String _jsonKeyRegisterUserId = 'id';

class RegisterUser {
/*
{
  "name": "Suman Shrestha",
  "email": "suman@gmail.com",
  "updated_at": "2022-04-05T07:44:12.000000Z",
  "created_at": "2022-04-05T07:44:12.000000Z",
  "id": 2
}
*/

  String? name;
  String? email;
  String? updatedAt;
  String? createdAt;
  int? id;
  Map<String, dynamic> __origJson = {};

  RegisterUser({
    this.name,
    this.email,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  RegisterUser.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    name = json[_jsonKeyRegisterUserName]?.toString();
    email = json[_jsonKeyRegisterUserEmail]?.toString();
    updatedAt = json[_jsonKeyRegisterUserUpdatedAt]?.toString();
    createdAt = json[_jsonKeyRegisterUserCreatedAt]?.toString();
    id = int.tryParse(json[_jsonKeyRegisterUserId]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyRegisterUserName] = name;
    data[_jsonKeyRegisterUserEmail] = email;
    data[_jsonKeyRegisterUserUpdatedAt] = updatedAt;
    data[_jsonKeyRegisterUserCreatedAt] = createdAt;
    data[_jsonKeyRegisterUserId] = id;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class Register {
/*
{
  "created": true,
  "user": {
    "name": "Suman Shrestha",
    "email": "suman@gmail.com",
    "updated_at": "2022-04-05T07:44:12.000000Z",
    "created_at": "2022-04-05T07:44:12.000000Z",
    "id": 2
  },
  "token": "8|kjQclR4P6IFTKcQUSbqRlpBOq3ET9kN0kaZDWKF0"
}
*/

  bool? created;
  RegisterUser? user;
  String? token;
  Map<String, dynamic> __origJson = {};

  Register({
    this.created,
    this.user,
    this.token,
  });
  Register.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    created = json[_jsonKeyRegisterCreated];
    user = (json[_jsonKeyRegisterUser] != null &&
            (json[_jsonKeyRegisterUser] is Map))
        ? RegisterUser.fromJson(json[_jsonKeyRegisterUser])
        : null;
    token = json[_jsonKeyRegisterToken]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyRegisterCreated] = created;
    if (user != null) {
      data[_jsonKeyRegisterUser] = user!.toJson();
    }
    data[_jsonKeyRegisterToken] = token;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
